# -*- coding: utf-8 -*-
"""WorldCloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V5Yo9ce9qAwOhNVI_irFQEkXeHLGsP9N
"""

# Exercice 1
# Author LF
# state : ongoing

# Exercice 2
# Author AK
# state : ongoing

# Exercice 3
# Author AM
# state : ongoing

